rondo:
    resource: "@RondoBundle/Resources/config/routing.yml"
    prefix:   /

#easy_admin_bundle:
#    resource: "@EasyAdminBundle/Controller/"
#    type:     annotation
#    prefix:   /easyadmin

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

# redirecting the root
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin
        permanent: true
