services:
    sonata.admin.song:
        class: Rondo\RondoBundle\Admin\SongAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Rondo", label: "Song" }
        arguments:
            - ~
            - Rondo\RondoBundle\Entity\Song
            - ~
        calls:
            - [ setTranslationDomain, [Rondo\RondoBundle]]